apiVersion: v1
kind: Secret
metadata:
  name: backend-env
  namespace: dataframe
type: Opaque
stringData:
  SESSION_SECRET: "asdfghjklqwertyuiopzxcvbnm1234567890"
  AUTH0_DOMAIN: "dev-yhkzu6l08ejl7p7e.us.auth0.com"
  AUTH0_CLIENT_ID: "bgmGtWAt7chFZ0zrHnhSWiqCSu8y7Olb"
  AUTH0_CLIENT_SECRET: "IqH9vPWzw9HsUUXR5FdchpZyvAiBVBljqMsV0EJwj1LhMsqYu-PsDHvih0l777lV"
  APP_BASE_URL: "https://216-128-144-40.sslip.io"
