apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dataframe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: backend
          image: ghcr.io/skz-04/jesb-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: SQLITE_FILE
              value: /data/database.db
          envFrom:
            - secretRef:
                name: backend-env
          volumeMounts:
            - name: backend-data
              mountPath: /data
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-data
